// src/routes/index.js
const express = require('express');
const authRoutes = require('./auth');
const quizRoutes = require('./quiz');
const adminRoutes = require('./admin');
const adminUsersRoutes = require('./admin-users');
const adminConfigRoutes = require('./admin-config');
const adminCategoriesRoutes = require('./admin-categories');
const adminCouponsRoutes = require('./admin-coupons');
const adminFaqsRoutes = require('./admin-faqs');
const adminStudyNotesRoutes = require('./admin-study-notes');
const adminAnnouncementRoutes = require('./admin-announcement');
const adminMarketingConsentRoutes = require('./admin-marketing-consent');
const adminWeeklyQuizRoutes = require('./admin-weekly-quiz');
const adminPreCouncilRoutes = require('./admin-pre-council');
const adminBadgesRoutes = require('./admin-badges');
const adminDashboardRoutes = require('./admin-dashboard');
const adminForceRefreshRoutes = require('./admin-force-refresh');
const weeklyQuizRoutes = require('./weekly-quiz');
const preCouncilRoutes = require('./pre-council');
const paymentRoutes = require('./payment');
const contactRoutes = require('./contact');
const announcementRoutes = require('./announcement');
const marketingConsentRoutes = require('./marketing-consent');
const privateMessageRoutes = require('./private-message');
const studyNotesRoutes = require('./study-notes');
const gamificationRoutes = require('./gamification');
const aiExplainRoutes = require('./ai-explain');
const userRoutes = require('./user');
const configRoutes = require('./config');
const categoriesRoutes = require('./categories');
const faqsRoutes = require('./faqs');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/quizzes', quizRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/users', adminUsersRoutes);
router.use('/admin/config', adminConfigRoutes);
router.use('/admin/categories', adminCategoriesRoutes);
router.use('/admin/coupons', adminCouponsRoutes);
router.use('/admin/faqs', adminFaqsRoutes);
router.use('/admin/study-notes', adminStudyNotesRoutes);
router.use('/admin/announcement', adminAnnouncementRoutes);
router.use('/admin/marketing-consent', adminMarketingConsentRoutes);
router.use('/admin/weekly-quiz', adminWeeklyQuizRoutes);
router.use('/admin/pre-council', adminPreCouncilRoutes);
router.use('/admin/badges', adminBadgesRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/admin/force-refresh', adminForceRefreshRoutes);
router.use('/weekly-quiz', weeklyQuizRoutes);
router.use('/pre-council', preCouncilRoutes);
router.use('/payment', paymentRoutes);
router.use('/contact', contactRoutes);
router.use('/announcement', announcementRoutes);
router.use('/marketing-consent', marketingConsentRoutes);
router.use('/private-messages', privateMessageRoutes);
router.use('/study-notes', studyNotesRoutes);
router.use('/gamification', gamificationRoutes);
router.use('/explain-question', aiExplainRoutes);
router.use('/user', userRoutes);
router.use('/config', configRoutes);
router.use('/categories', categoriesRoutes);
router.use('/faqs', faqsRoutes);

module.exports = router;